### ISSUE TITLE
Scraper picking up the licencing master list

### ISSUE THREAD

**Issue by thebassettman** [lselden/scp-to-epub#1]
Recently I've noticed this picking up [the licencing master list](http://www.scp-wiki.net/licensing-master-list) when converting more recent pages.

**Comment by lselden** [comment]
Thanks for the report @thebassettman. I just [pushed](https://github.com/lselden/scp-to-epub/commit/147034bd533bcbb7226b3d5da328a30ecd56d3a9) an update to ignore that page.

Just FYI if you ever need to avoid this in the future you can add a page to the [`exclude` parameter in the config file](https://github.com/lselden/scp-to-epub/blob/147034bd533bcbb7226b3d5da328a30ecd56d3a9/config.yaml#L58):
```yaml
discovery:
  ### never include these articles
  exclude: ["licensing-master-list", "some-other-page"]
```
